name: Latest Project Videos
on:
  schedule: # Run every day
    - cron: '0 * * * *' # Runs every hour, on the hour
    workflow_dispatch:
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
        comment_tag_name: "Itvlog"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=fH5h_6uuXlA"